### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by behoof** [Syxton/moodle-filter_sectionnames#1]
L.s.

I'm using Moodle 3.3+ (Build: 20170629)
Using the plugin I'm getting Internal Server Errors and could not use custom Languages.

Apache gives: [Fri Aug 18 14:22:25.660170 2017] [proxy_fcgi:error] [pid 20007:tid 139992481384192] [client 128.140.222.210:37351] AH01071: Got error 'PHP message: PHP Notice: Trying to get property of non-object in /home/prox6user/domains/prox6.academy/public_html/filter/sectionnames/filter.php on line 96\n'

Disabling your plugin solved my issue. Which is a pity!

**Comment by Syxton** [comment]
@behoof Sorry the plugin is giving you issues.  What course format are you using?

**Comment by behoof** [comment]
Hi,

I', using onetopic
I can't reproduce the error after I switchted to PHP 7 (was using 5.6) 
So issue can be closed for now

Bert
