### ISSUE TITLE
unit test failures with sectionnames installed.

### ISSUE THREAD

**Issue by danmarsden** [Syxton/moodle-filter_sectionnames#2]
I'm seeing these unit test failures in both a 3.1 and a 3.5 site.

Trying to get property of non-object

/var/www/html/filter/sectionnames/filter.php:96
/var/www/html/lib/filterlib.php:176
/var/www/html/lib/filterlib.php:218
/var/www/html/lib/weblib.php:1284

Here are some of the unit tests that fail with the above error:

core_calendar_externallib_testcase::test_get_calendar_events
core_question_events_testcase::test_question_category_created
random_question_loader_testcase::test_random_questions_not_returned
core_comment_externallib_testcase::test_get_comments
core_course_courselib_testcase::test_course_delete_module
core_course_externallib_testcase::test_get_courses

**Comment by Syxton** [comment]
@danmarsden Thank you for the report.  So far I have run those unit test and not received an error from sectionnames plugin.  I'm running Moodle 3.5.1+ (Build: 20180803) in a XAMPP for Windows on my machine.  

This was the results of my run:
[unittestrun1.txt](https://github.com/Syxton/moodle-filter_sectionnames/files/2353914/unittestrun1.txt)

**Comment by danmarsden** [comment]
yeah - I suspect there's a bug with a course format that is returning an unexpected numsections value due to the way it handles sections.

you should probably check that $modinfo->get_section_info($section) is not empty before checking the visible param.

the site that is triggering this also has "onetopic/grid/tabtopics" custom formats installed. (I suspect tabtopics is probably the culprit)

**Comment by Syxton** [comment]
@danmarsden Ok, I have added a check, I'll look to add support in the future.  Thanks.  Check to see if this passes the tests before I close.

**Comment by danmarsden** [comment]
thanks - passes on our 3.1 and 3.5 branches for this client now!
