### ISSUE TITLE
3.5 unit test failure when sectionnames plugin installed

### ISSUE THREAD

**Issue by danmarsden** [Syxton/moodle-filter_sectionnames#3]
This seems a bit weird - I suspect this is an upstream bug where resetAfterTest isn't triggered properly  but the sectionnames plugin seems to trigger it. (removing the sectionnames plugin seems to clear it.)

Just adding some detail here in case someone else has run into this as well?

---------

There was 1 failure:

1) core_course_externallib_testcase::test_get_courses_by_field
Failed asserting that actual size 4 matches expected size 3.

/var/www/html/course/tests/externallib_test.php:2156
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

**Comment by danmarsden** [comment]
looks like this is the cause:
https://github.com/Syxton/moodle-filter_sectionnames/blob/master/db/install.php#L36

one option would be to not set that if the site is running phpunit tests..

**Comment by Syxton** [comment]
@danmarsden I haven't had much time to look into this, but I wonder why this filter runs into this problem, but the activitynames filter doesn't.

**Comment by Syxton** [comment]
@danmarsden It looks like the test is looking for the default filters and apparently there should only be 3.  Should db/install.php look more like the glossary filter? 

// Check default filters.
        $this->assertCount(3, $result['courses'][0]['filters']);
        $this->assertCount(3, $result['courses'][1]['filters']);

**Comment by danmarsden** [comment]
yeah - the core test is a bit fragile - I'm not clear if all people that install your filter will want to enable it at the site level though - I guess you'll need to decide that yourself - should people have to explicitly enable the plugin where they want (and be aware of any performance impacts etc.) or will they all want to enable it at the site level anyway, so doing this in the install.php just makes it easier for your users to install the plugin.

**Comment by Syxton** [comment]
@danmarsden Just confirmed that this does in fact fix the issue.  The REAL issue is that the unit test only allows for 3 site level filters.  Not sure why that is.

**Comment by danmarsden** [comment]
yeah - just a badly written unit test I think. Assuming that filter plugins will not enable themselves on install.

**Comment by Syxton** [comment]
@danmarsden ok, thanks for the report!
