### ISSUE TITLE
Call to undefined function course_get_format() 

### ISSUE THREAD

**Issue by behoof** [Syxton/moodle-filter_sectionnames#4]
L.s.

On installing I get the generalexceptionmessage. 

Call to undefined function course_get_format() 

Debug info:
    line 91 of /filter/sectionnames/filter.php: Error thrown
    line 176 of /lib/filterlib.php: call to filter_sectionnames->filter()
    line 232 of /lib/filterlib.php: call to filter_manager->apply_filter_chain()
    line 1464 of /lib/weblib.php: call to filter_manager->filter_string()
    line 9 of /theme/maker/layout/login.php: call to format_string()
    line 1287 of /lib/outputrenderers.php: call to include()
    line 1217 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 1881 of /lib/setuplib.php: call to core_renderer->header()
    line 338 of /login/index.php: call to bootstrap_renderer->__call()

I'm using the maker theme and the grid course format. Using Moodle 3.5.3+ (Build: 20181120)

Bert

**Comment by Syxton** [comment]
@behoof I can confirm that the sectionnames filter doesn't really work for the grid format, since links to the grid sections aren't normal links, they are some kind of javascript popup thing.  However, I haven't been able to recreate your specific error.  What version of Moodle are you running?

**Comment by Syxton** [comment]
@behoof Can you install the commit I just posted and see if it still gives the error.  It won't work in grid format, but I'm trying stop the error too.

**Comment by behoof** [comment]
Hi,

Quick action!

On login it gives the error: Class 'format_base' not found

Bert

**Comment by Syxton** [comment]
@behoof  Ok, I'll keep looking.

**Comment by Syxton** [comment]
@behoof Can you install the commit I just posted and see if it still gives the error.  I'm now making 100% sure that format/lib.php is included.  You should definitely have course_get_format()
